### ISSUE TITLE
Where is Google Chrome download link

### ISSUE THREAD

**Issue by trinhpham** [vikyd/download-chromium-history-version#1]
Hi @vikyd ,

Your repository is very helpful to me. But I found no download link of official Google Chrome yet.
I wonder if we can have older version of Google Chrome (not Chromium), can't we?

Regards,

**Comment by vikyd** [comment]
I have no way.

**Comment by trinhpham** [comment]
Thank @vikyd for taking your time to reply me.
Closed as this is not an issue.
